<?php
// $Id$

/**
 * @file
 * Builds scaffolding for custom modules.
 */

/**
 * Index into MODULE_BUILDER_EXTRACT_HOOK_PATTERN capture list that returns the hook description from the hook files.
 */
define('MODULE_BUILDER_HOOK_DESCRIPTIONS', 1);
/**
 * Index into MODULE_BUILDER_EXTRACT_HOOK_PATTERN capture list that returns the hook declaration from the hook files.
 */
define('MODULE_BUILDER_HOOK_DECLARATIONS', 2);
/**
 * Index into MODULE_BUILDER_EXTRACT_HOOK_PATTERN capture list that returns the hook name from the hook files.
 */
define('MODULE_BUILDER_HOOK_NAMES', 3);

/**
 * Version of hook info to retrieve 
 */
define('MODULE_BUILDER_VERSION', 'HEAD');

/* Constant values extracted from code */
/**
 * Base URL for accessing Drupal CVS.
 */
define('MODULE_BUILDER_CVS_URL', 'http://cvs.drupal.org');
/**
 * URL for retreiving the hook description files.
 */
define('MODULE_BUILDER_HOOKS_URL', MODULE_BUILDER_CVS_URL .'/viewcvs/drupal/contributions/docs/developer/hooks/?only_with_tag='. MODULE_BUILDER_VERSION);
/**
 * Pattern for finding the hook file URLs from the MODULE_BUILDER_HOOKS_URL page.
 */
define('MODULE_BUILDER_URL_PATTERN', '!<td>\&nbsp;<a href="(.*?)"!');
/**
 * Pattern that captures 3 things about a hook from one of the hook files: Description, Declaraion and Name (in that order).
 */
define('MODULE_BUILDER_EXTRACT_HOOK_PATTERN', '#\/\*\*\n \* (\w.*?)\s+\*\s+\*.*?(function (hook_.*?)\(.*?\) {)#ms');
/**
 * After finding a hook file URL with MODULE_BUILDER_URL_PATTERN, this captures the path and filename.
 */
define('MODULE_BUILDER_FILE_PATTERN', '!(.*)/(.*?)\?!');
/**
 * In case we have an expanded CVS Id, this matches that, and captures the version number (although we don't use that). This is then replaced with MODULE_BUILDER_ID_COMMENT.
 */
define('MODULE_BUILDER_FULL_ID_PATTERN', '#\/\/ \$Id(.*?)\$#');
/**
 * Took this regex from the PHP manual page on Functions
 */
define('MODULE_BUILDER_FUNCTION_PATTERN', '#^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*#');
/**
 * Used to strip INFO messages out of generated file for advanced users.
 */
define('MODULE_BUILDER_INFO_PATTERN', '#(\s+)\/\* INFO:(.*?)\*\/#ms');
/**
 * Captures a template name and body from a template file.
 */
define('MODULE_BUILDER_TEMPLATE_PATTERN', '#== START (.*?) ==(.*?)== END ==#ms');
/**
 * Path from module base to the module builder css file.
 */
define('MODULE_BUILDER_CSS_PATH', '/includes/module_builder.css');
/**
 * Path from module base to the module builder java script file.
 */
define('MODULE_BUILDER_JS_PATH', '/includes/module_builder.js');
/**
 * Path from module base to the normal hook groups template. MODULE_BUILDER_CUSTOM_HOOK_GROUPS_TEMPLATE_PATH used if it exists.
 */
define('MODULE_BUILDER_HOOK_GROUPS_TEMPLATE_PATH', '/templates/hook_groups.template');
/**
 * Path from module base to the custom hook groups template. Only used if it exists, otherwise MODULE_BUILDER_HOOK_GROUPS_TEMPLATE_PATH is used.
 */
define('MODULE_BUILDER_CUSTOM_HOOK_GROUPS_TEMPLATE_PATH', '/template/hook_groups-custom.template');
/**
 * Used to replace a full CVS Id tag with a starter ID.
 */
// The weird syntax stops this from getting mangled by CVS
define('MODULE_BUILDER_ID_COMMENT', '// $'.'Id$');


/* Default variable names and their default values */
define('MODULE_BUILDER_DETAIL_VARIABLE', 'module_builder_detail');
define('MODULE_BUILDER_DETAIL_DEFAULT', 0);
define('MODULE_BUILDER_FILE_DIRECTORY_PATH_VARIABLE', 'file_directory_path');
define('MODULE_BUILDER_FILE_DIRECTORY_PATH_DEFAULT', 'files');
define('MODULE_BUILDER_HOOKS_DIRECTORY_VARIABLE', 'module_builder_hooks_directory');
define('MODULE_BUILDER_HOOKS_DIRECTORY_DEFAULT', 'hooks');
define('MODULE_BUILDER_HEADER_VARIABLE', 'module_builder_header');
define('MODULE_BUILDER_HEADER_DEFAULT', '// $'.'Id$

/**
 * @file
 * TODO: Enter file description here.
 */
');
define('MODULE_BUILDER_FOOTER_VARIABLE', 'module_builder_footer');
define('MODULE_BUILDER_FOOTER_DEFAULT', '');
define('MODULE_BUILDER_DOWNLOAD_VARIABLE', 'module_builder_download');
define('MODULE_BUILDER_DOWNLOAD_DEFAULT', 1);
define('MODULE_BUILDER_LAST_UPDATE_VARIABLE', 'module_builder_last_udpate');
define('MODULE_BUILDER_LAST_UPDATE_DEFAULT', 0);

/**
 * @defgroup module_builder_core Core Drupal hooks
 */

/**
 * Implementation of hook_perm().
 *
 * @ingroup module_builder_core
 */
function module_builder_perm() {
  return array('access module builder');
}

/**
 * Implementation of hook_menu().
 *
 * @ingroup module_builder_core
 */
function module_builder_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array(
      'path' => 'module_builder',
      'title' => t('Module builder'),
      'description' => t('Builds scaffolding for custom modules.'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('module_builder_page'),
      'access' => user_access('access module builder'),
      'type' => MENU_NORMAL_ITEM,
    );
    $items[] = array(
      'path' => 'admin/settings/module_builder',
      'title' => t('Module builder'),
      'description' => t('Set default header and footer, api download location, defaults for detail and download and force the api to be re-downloaded.'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('module_builder_admin_settings'),
      'access' => user_access('access module builder'),
      'type' => MENU_NORMAL_ITEM,
    );
    $items[] = array(
      'path' => 'module_builder_process',
      'title' => t('Module builder'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('module_builder_process'),
      'access' => user_access('access module builder'),
      'type' => MENU_CALLBACK,
    );
  }

  return $items;
}

/**
 * Implementation of hook_settings().
 *
 * @ingroup module_builder_core
 */
function module_builder_admin_settings() {

  $form['module_builder_hooks_directory'] = array(
    '#type' => 'textfield',
    '#title' => t('Path to hook documentation directory'),
    '#description' => t('Subdirectory in the directory "%dir" where local copies of hook documentation should be stored.', array('%dir' => variable_get(MODULE_BUILDER_FILE_DIRECTORY_PATH_VARIABLE, MODULE_BUILDER_FILE_DIRECTORY_PATH_DEFAULT) .'/')),
    '#default_value' => variable_get(MODULE_BUILDER_HOOKS_DIRECTORY_VARIABLE, MODULE_BUILDER_HOOKS_DIRECTORY_DEFAULT),
  );
  $form['module_builder_header'] = array(
    '#type' => 'textarea',
    '#title' => t('Module header'),
    '#description' => t('This is the code that will be displayed at the top of your module file.'),
    '#rows' => 15,
    '#default_value' => variable_get(MODULE_BUILDER_HEADER_VARIABLE, MODULE_BUILDER_HEADER_DEFAULT),
  );
  $form['module_builder_footer'] = array(
    '#type' => 'textarea',
    '#title' => t('Module footer'),
    '#description' => t('This is the code that will be displayed at the bottom of your module file.'),
    '#rows' => 15,
    '#default_value' => variable_get(MODULE_BUILDER_FOOTER_VARIABLE, MODULE_BUILDER_FOOTER_DEFAULT),
  );
  $form['module_builder_detail'] = array(
    '#type' => 'radios',
    '#title' => t('Code detail level'),
    '#description' => t('This setting will either display or suppress additional explanatory comments in the resulting module code to help new developers.'),
    '#options' => array(
      1 => t("<strong>Beginner</strong>: I'm just starting out with Drupal development; please display lots of helpful comments in my module code!"),
      0 => t("<strong>Advanced</strong>: I already know what I'm doing; don't put in a bunch of crap in my module file that I don't need!"),
    ),
    '#default_value' => variable_get(MODULE_BUILDER_DETAIL_VARIABLE, MODULE_BUILDER_DETAIL_DEFAULT),
  );
  $form['module_builder_download'] = array(
    '#type' => 'radios',
    '#title' => t('Download module file checkbox defaults to'),
    '#description' => t('When checked, this will automatically generate your module file for you and prompt your browser to download it.'),
    '#options' => array(
      1 => t('Enabled'),
      0 => t('Disabled'),
    ),
    '#default_value' => variable_get(MODULE_BUILDER_DOWNLOAD_VARIABLE, MODULE_BUILDER_DOWNLOAD_DEFAULT),
  );
  $form['module_builder_update'] = array(
    '#type' => 'fieldset',
    '#title' => t('Update hook documentation'),
    '#description' => t('Your last hook documentation update was %date.', array('%date' => variable_get(MODULE_BUILDER_LAST_UPDATE_VARIABLE, MODULE_BUILDER_LAST_UPDATE_DEFAULT))),
  );
  $form['module_builder_update']['update'] = array(
    '#type' => 'submit',
    '#value' => t('Update'),
  );

  return system_settings_form($form);

}

/**
 * Implementation of submit handler for settings page.
 *
 * @ingroup module_builder_core
 */
function module_builder_admin_settings_submit($form_id, $form_values) {
  if ($form_values['op'] == t('Update')) {
    module_builder_update_documentation();
    drupal_set_message(t('Hook documentation has been updated.'));
  }
  // In order to get regular settings page processing we need to 
  // pass controll off to the system.module submit handler.
  return system_settings_form_submit($form_id, $form_values);
}

/**
 * Create a directory to store hook files if it does not exist.
 *
 * This logic blatantly ripped off from image.module -- thanks James! :)
 */
function _module_builder_check_settings() {
  $hooks_path = file_create_path(variable_get(MODULE_BUILDER_HOOKS_DIRECTORY_VARIABLE, MODULE_BUILDER_HOOKS_DIRECTORY_DEFAULT));
  file_check_directory($hooks_path, FILE_CREATE_DIRECTORY, 'module_builder_hooks_directory');
  $last_update = variable_get(MODULE_BUILDER_LAST_UPDATE_VARIABLE, MODULE_BUILDER_LAST_UPDATE_DEFAULT);
  if (!$last_update) {
    module_builder_update_documentation();
    drupal_set_message(t("Module Builder has just downloaded hook documentation to your %dir directory from CVS. This documentation contains detailed descriptions and usage examples of each of Drupal's hooks. Please view the files for more information, or view them online at the <a href=\"!api\">Drupal API documentation</a> site.", array('%dir' => 'files/'. variable_get(MODULE_BUILDER_HOOKS_DIRECTORY_VARIABLE, MODULE_BUILDER_HOOKS_DIRECTORY_DEFAULT), '!api' => url('http://api.drupal.org/api/HEAD', NULL, NULL, TRUE))));
  }
}

/**
 * @defgroup module_builder_callback Functions which are the menu callbacks for this module
 */

/**
 * Displays module builder interface.
 *
 * @ingroup module_builder_callback
 * @return
 *   Form for entering module options
 */
function module_builder_page() {

  _module_builder_check_settings();

  // Include CSS for formatting
  drupal_add_css(drupal_get_path('module', 'module_builder') . MODULE_BUILDER_CSS_PATH);

  // Module properties
  $form['module_root_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Module root name'),
    '#description' => t('All of your functions will be prefixed with this string. This name must only contain letters, numbers, and underscores, and may not start with a number.'),
    '#required' => TRUE,
  );
  $form['module_short_description'] = array(
    '#type' => 'textfield',
    '#title' => t('Module short description'),
    '#description' => t('Will appear in the module listing at <a href="!listing">%administer >> %build >> %modules</a>.', array('!listing' => url('admin/build/modules'), '%administer' => 'Administer', '%build' => 'Site building', '%modules' => 'Modules')),
    '#required' => TRUE,
  );
  $form['module_readable_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Module readable name'),
    '#description' => t('Name of your module as it will appear to users. (Note: only for node modules)'),
  );
  $form['module_help_text'] = array(
    '#type' => 'textarea',
    '#title' => t('Help text'),
    '#description' => t('Help text (HTML) to appear in <a href="!help">%administer >> %help >> module_name</a> page', array('!help' => url('admin/help'), '%administer' => 'Administer', '%help' => 'Help')),
  );

  // Check for custom hook_groups file, else use default
  $path = drupal_get_path('module', 'module_builder');
  if (file_exists($path . MODULE_BUILDER_CUSTOM_HOOK_GROUPS_TEMPLATE_PATH)) {
    $template_file = file_get_contents($path . MODULE_BUILDER_CUSTOM_HOOK_GROUPS_TEMPLATE_PATH);
  }
  else {
    $template_file = file_get_contents($path . MODULE_BUILDER_HOOK_GROUPS_TEMPLATE_PATH);
  }

  $form['hook_groups'] = array(
    '#type' => 'fieldset',
    '#title' => t('Hook groupings'),
    '#description' => t('Selecting one or more of these features will automatically select appropriate hooks for you.'),
  );

  drupal_add_js($path . MODULE_BUILDER_JS_PATH);

  // Get list of hook groups
  $hook_groups = module_builder_parse_template($template_file);
  $count = count($hook_groups);
  for ($i = 0; $i < $count; $i++) {
    $hooks = explode("\n", $hook_groups[$i]['data']);
    $hook_array = array();
    foreach ($hooks as $hook) {
      $hook = trim($hook);
      if (!empty($hook)) {
        $hook_array[] = "'$hook'";
      }
    }

    $form['hook_groups']['groups-'. $i] = array(
      '#type' => 'checkbox',
      '#title' => $hook_groups[$i]['title'],
      '#attributes' => array(
        'onclick' => 'check_hooks(this, ['. implode(', ', $hook_array) .'])',
      ),
      //'#description' => $hook_groups[$i]['data'],

      // TODO: For some reason this gives me some wacky error under PHP 5:
      // Fatal error: Cannot use string offset as an array
      //'#default_value' => $edit['hook_groups'][$i],
    );
  }

  // Get list of hooks
  $hook_groups = module_builder_get_hook_data();

  if (!is_array($hook_groups) || !count($hook_groups)) {
    form_set_error('hooks', t('No hooks were found. Please check the documentation path specified in the <a href="!settings">%administer >> %settings >> %modulebuilder</a> page.', array('!settings' => url('admin/settings/module_builder'), '%administer' => 'Administer', '%settings' => 'Site configuration', '%modulebuilder' => "Module builder")));
  }
  else {

    // Build hooks list
    $form['hooks'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Use the following specific hooks'),
    );

    foreach ($hook_groups as $hook_group => $hooks) {
      $form['hooks'][$hook_group] = array(
        '#type' => 'fieldset',
        '#title' => $hook_group .' hooks',
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
        '#prefix' => '<ul class="hook-group">',
        '#suffix' => '</ul><br clear="all" />',
      );
      foreach ($hooks as $hook) {
        $name = $hook['name'];
        $desc = $hook['description'];
        $form['hooks'][$hook_group][$name] = array(
          '#type' => 'checkbox',
          '#title' => str_replace('hook_', '', $name),
          '#description' => $desc,
          '#attributes' => array(
            'id' => "edit-hooks-$name",
          ),
          '#prefix' => '<li>',
          '#suffix' => '</li>',

          // TODO: For some reason this gives me some wacky error under PHP 5:
          // Fatal error: Cannot use string offset as an array
          //'#default_value' => $edit['hooks'][$hook_group][$hook],

          // TODO: I would *like* to do something like the following, so some of the long
          // descriptions don't totally mangle the page output, but need a way to do like
          // a "onmouseover" effect to display the full thing. Note that 'title' is not
          // a valid attribute for divs. :\
          //'#description' => truncate_utf8($desc, 40, TRUE, TRUE),

        );
        // Set some default hooks
        if ($name == 'hook_help' || $name == 'hook_menu') {
          $form['hooks'][$hook_group][$name]['#default_value'] = 1;
        }
      }
      // Sort list alphabetically
      ksort($form['hooks'][$hook_group]);
    }

    $form['download'] = array(
      '#type' => 'checkbox',
      '#title' => t('Automatically generate module file for download?'),
      '#description' => t('When checked, this will automatically generate your module file for you and prompt your browser to download it.'),
      '#default_value' => variable_get(MODULE_BUILDER_DOWNLOAD_VARIABLE, MODULE_BUILDER_DOWNLOAD_DEFAULT),
    );
    $form['op'] = array(
      '#type' => 'submit',
      '#value' => t('Submit'),
    );
  }

  return $form;
}

/**
 * Makes sure that valid values have been provided to the Module Builder.
 * 
 * @ingroup module_builder_callback
 */
function module_builder_page_validate($form_id, $form_values) {
  // Ensure module_root_name was entered, and check for special characters
  if (!empty($form_values['module_root_name'])) {
    if (!preg_match(MODULE_BUILDER_FUNCTION_PATTERN, $form_values['module_root_name'])) {
      form_set_error('module_root_name', t('The module root name must only contain letters, numbers, and underscores, and may not start with a number.'));
    }
  }

  // Make sure at least one hook was chosen
  $hook_selected = false;
  foreach ($form_values['hooks'] as $file => $hooks) {
    foreach ($hooks as $hook) {
      if ($hook == 1) {
        $hook_selected = true;
        break;
      }
    }
    if ($hook_selected) {
      break;
    }
  }
  if (!$hook_selected) {
    form_set_error('hooks', t('You must select at least one hook.'));
  }
}

/**
 * Passes control from a valid Module Builder submission to the module_builder_process 
 * which will actually generate the module and deliver it to the user.
 * 
 * @ingroup module_builder_callback
 */
function module_builder_page_submit($form_id, $form_values) {
  $_SESSION['module_builder_values'] = $form_values;
  $_SESSION['module_builder_is_node'] = $form_values['hooks']['node']['hook_node_info'];
  return 'module_builder_process';
}

/**
 * Generate module file
 * 
 * @ingroup module_builder_callback
 */
function module_builder_process() {

  if (isset($_SESSION['module_builder_values'])) {
    $edit = $_SESSION['module_builder_values'];
    unset($_SESSION['module_builder_values']);
  }
  else {
    drupal_goto('module_builder');
  }

  // Include link in breadcrumb to go back to main module builder form
  $breadcrumb = drupal_get_breadcrumb();
  $breadcrumb[] = l(t('Module Builder'), 'module_builder');
  drupal_set_breadcrumb($breadcrumb);

  // Grab header from settings
  $header = "<?php\n". variable_get(MODULE_BUILDER_HEADER_VARIABLE, MODULE_BUILDER_HEADER_DEFAULT);

  // Grab footer from settings
  $footer = variable_get(MODULE_BUILDER_FOOTER_VARIABLE, MODULE_BUILDER_FOOTER_DEFAULT);

  // Check for custom functions file, else use default
  $path = drupal_get_path('module', 'module_builder') .'/templates';
  if (file_exists("$path/hooks-custom.template")) {
    $template_file = file_get_contents("$path/hooks-custom.template");
  }
  else {
    $template_file = file_get_contents("$path/hooks.template");
  }

  // Get array of default hook declarations
  $hook_default_declarations = module_builder_get_hook_data(MODULE_BUILDER_HOOK_DECLARATIONS);

  // Get array of custom hook declarations
  $custom_hooks = module_builder_parse_template($template_file);
  foreach ($custom_hooks as $hook) {
    $hook_custom_declarations[$hook['title']] = $hook['data'];
  }

  // Check for node hooks; these will overwrite core hooks if found
  if ($_SESSION['module_builder_is_node']) {
    if (file_exists("$path/node_hooks-custom.template")) {
      $template_file = file_get_contents("$path/node_hooks-custom.template");
    }
    else {
      $template_file = file_get_contents("$path/node_hooks.template");
    }
    $custom_hooks = module_builder_parse_template($template_file);
    foreach ($custom_hooks as $hook) {
      $hook_custom_declarations[$hook['title']] = $hook['data'];
    }
  }
  unset($_SESSION['module_builder_is_node']);

  // Strip out INFO: comments for advanced users
  if (!variable_get(MODULE_BUILDER_DETAIL_VARIABLE, MODULE_BUILDER_DETAIL_DEFAULT)) {
    foreach ($hook_custom_declarations as $hook => $data) {
      $hook_custom_declarations[$hook] = preg_replace(MODULE_BUILDER_INFO_PATTERN, '', $data);
    }
  }

  // Begin code generation
  $code = '';

  // Determine which hooks are to be implemented
  foreach ($edit['hooks'] as $hooks) {
    foreach ($hooks as $hook => $value) {
      if ($value) {
        // Display PHP doc
        $code .= "
/**
 * Implementation of $hook().
 */
";

        $code .= str_replace('hook', $edit['module_root_name'], $hook_default_declarations[$hook]);
        // See if function bodies exist; if so, use function bodies from template
        if (array_key_exists($hook, $hook_custom_declarations)) {
          $code .= $hook_custom_declarations[$hook];
        }
        else {
          $code .= "\n\n";
        }
        $code .= "}\n\n";
      }
    }
  }

  // Replace variables
  $variables = array(
    '%module' => $edit['module_root_name'],
    '%description' => str_replace("'", "\'", $edit['module_short_description']),
    '%name' => !empty($edit['module_readable_name']) ? str_replace("'", "\'", $edit['module_readable_name']) : $edit['module_root_name'],
    '%help' => !empty($edit['module_help_text']) ? str_replace("'", "\'", $edit['module_help_text']) : t('TODO: Create admin help text.'),
    '%readable' => str_replace("'", "\'", $edit['module_readable_name']),
  );
  $code = strtr($code, $variables);

  // Replace full-blown Id tag with just starter
  // (excuse the weird concatenation stuff; CVS hijacks it otherwise :))
  $code = preg_replace(MODULE_BUILDER_FULL_ID_PATTERN, MODULE_BUILDER_ID_COMMENT, $code);

  // Prepare final code
  $code = $header . $code . $footer;
  
  $form['page_instructions'] = array(
    '#value' => t('Please copy and paste the following text into a file called !module.', array('!module' => $edit['module_root_name'] . '.module')),
    '#prefix' => '<div id="module-message">',
    '#suffix' => '</div>',
  ); 
  $form['module_code'] = array(
    '#type' => 'textarea',
    '#title' => t('Module Code'),
    '#rows' => 20,
    '#default_value' => $code,
    '#prefix' => '<div id="module-code">',
    '#suffix' => '</div>',
  );

  return $form;
}

/**
 * !!!
 * Need to move this logic somewhere so we can download several files, one at 
 * a time, or all at once via some zipping mechanism.
 */
function download_file() {
  // Check if file was selected for download; if so, send to browser
  if ($edit['download']) {
    $file_content= $output;
    $download_file= $edit['module_root_name'] .'.module';
    header("Content-disposition: attachment; filename=$download_file");
    header('Content-Type: application/force-download');
    header('Content-Transfer-Encoding: binary');
    header('Content-Length: '. strlen($filecontent));
    header('Pragma: no-cache');
    header('Expires: 0');
    echo $file_content;
    exit();
  }
}

/**
 * Parse a module_builder template file.
 *
 * Template files are composed of several sections in the form of:
 *
 * == START [title of template section] ==
 * [the body of the template section]
 * == END ==
 *
 * @param string $file
 *   The template file to parse
 * @return Array
 *   Return array of template section titles and their associated data
 */
function module_builder_parse_template($file) {
  $hook_custom_declarations = array();
  preg_match_all(MODULE_BUILDER_TEMPLATE_PATTERN, $file, $matches);
  $count = count($matches[0]);
  for ($i = 0; $i < $count; $i++) {
    $hook_custom_declarations[] = array(
      'title' => $matches[1][$i],
      'data' => $matches[2][$i]
    );
  }
  return $hook_custom_declarations;
}


/**
 * Retrieves hook data of given type
 *
 * @return
 *   Array of hook info
 */
function module_builder_get_hook_data($type = MODULE_BUILDER_HOOK_NAMES) {
  // Find path of hook documentation directory
  $path = file_create_path(variable_get(MODULE_BUILDER_HOOKS_DIRECTORY_VARIABLE, MODULE_BUILDER_HOOKS_DIRECTORY_DEFAULT)) .'/';

  // Get list of hook documentation files
  $files = module_builder_get_doc_files($path);
  if (!isset($files)) {
    return NULL;
  }

  // Build list of hooks
  $hook_groups = array();
  foreach ($files as $file) {
    $hook_data = module_builder_extract_hook_data($path, $file, $type);
    if ($type == MODULE_BUILDER_HOOK_NAMES) {
      // Obtain list of descriptions
      $descriptions = module_builder_extract_hook_data($path, $file, MODULE_BUILDER_HOOK_DESCRIPTIONS);
      $file_name = substr($file, 0, strrpos($file, '.'));
      // Create an array in the form of:
      // array(
      //   'filename' => array(
      //     array('hook' => 'hook_foo', 'description' => 'hook_foo description'),
      //     ...
      //   ),
      //   ...
      // );
      foreach ($hook_data as $key => $hook) {
        // Remove extra "* " for multi-line descriptions
        $description = str_replace('* ', '', $descriptions[$key]);
        $hook_groups[$file_name][$key] = array('name' => $hook, 'description' => $description);
      }
    }
    elseif ($type == MODULE_BUILDER_HOOK_DECLARATIONS)  {
      $hook_names = module_builder_extract_hook_data($path, $file, MODULE_BUILDER_HOOK_NAMES);
      // Create an array in the form of:
      // array(
      //   'hook_foo' => 'function hook_foo( ... ) {',
      //     ...
      // );
      foreach ($hook_data as $key => $declaration) {
        $hook_groups[$hook_names[$key]] = $declaration;
      }
    }
  }

  return $hook_groups;
}

/**
 * Retrieve list of documentation files containing hook definitions.
 *
 * @param string $path
 *   Path to the hooks documentation directory
 * @return array
 *   Array of files
 */
function module_builder_get_doc_files($path) {
  if (!$path) {
    drupal_set_message(t('Please configure the hook documentation path in <a href="!settings">module builder settings</a>.', array('!settings' => url('admin/settings/module_builder'))), 'error');
    return NULL;
  }

  $files = array();

  if (is_dir($path)) {
    if ($dh = opendir($path)) {
      while (($file = readdir($dh)) !== false) {
        // Ignore files that don't make sense to include
        if ($file != '.' && $file != '..' && $file != 'CVS' && $file != 'install.php') {
          $files[] = $file;
        }
      }
      closedir($dh);
    }
    else {
      drupal_set_message(t('There was an error opening the hook documentation path. Please try again.'), 'error');
      return NULL;
    }
  }
  else {
    drupal_set_message(t('Hook documentation path is invalid. Please return to the <a href="!settings">module builder settings</a> page to try again.', array('!settings' => url('admin/settings/module_builder'))), 'error');
    return NULL;
  }

  return $files;
}

/**
 * Extracts hook information based on type parameter.
 *
 * @param string $path
 *   Path to hook file
 * @param string $file
 *   Name of hook file
 * @param string $type
 *   Type of hook data to extract. This is one of three values:
 *   * 1 - MODULE_BUILDER_HOOK_DESCRIPTIONS: Each hook's user-friendly description
 *   * 2 - MODULE_BUILDER_HOOK_DECLARATIONS: Each hook's entire function declaration
 *   * 3 - MODULE_BUILDER_HOOK_NAMES: The names of each hook
 * @return array
 *   Array of hook data
 */
function module_builder_extract_hook_data($path, $file, $type = MODULE_BUILDER_HOOK_NAMES) {
  $contents = file_get_contents($path . $file);

  // This match contains three sub-patterns, each corresponding to a constant which
  // describes which data to extract
  preg_match_all(MODULE_BUILDER_EXTRACT_HOOK_PATTERN, $contents, $matches);

  return $matches[$type];
}

/**
 * Initiates documentation upate routine.
 */
function module_builder_update_documentation() {
  // Retrieve remote hook file listing from cvs.drupal.org
  $hook_listing = drupal_http_request(MODULE_BUILDER_HOOKS_URL);
  if (isset($hook_listing->error)) {
    return FALSE;
  }
  $hook_files = array();

  // Parse out list of URLs
  preg_match_all(MODULE_BUILDER_URL_PATTERN, $hook_listing->data, $url_matches);
  foreach ($url_matches[1] as $url_match) {

    // Parse out file name
    preg_match(MODULE_BUILDER_FILE_PATTERN, $url_match, $file_matches);

    // Store value of URL to hook documentation file and its name
    $hook_file_url = MODULE_BUILDER_CVS_URL . $url_match;
    $hook_file_name = $file_matches[2];
    $hook_files[$hook_file_name] = $hook_file_url;
  }

  // Retrieve each file and store it in the hooks directory, overwriting what's currently there
  $directory = file_create_path(variable_get(MODULE_BUILDER_HOOKS_DIRECTORY_VARIABLE, MODULE_BUILDER_HOOKS_DIRECTORY_DEFAULT));
  foreach ($hook_files as $file_name => $file_url) {
    $file_contents = drupal_http_request($file_url);
    file_save_data($file_contents->data, "$directory/$file_name", FILE_EXISTS_REPLACE);
  }

  // Finally, set the last updated variable
  variable_set(MODULE_BUILDER_LAST_UPDATE_VARIABLE, format_date(time()));
}
