<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class DrupalCodeBuilderCompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'environment' => 'get1',
  'DrupalCodeBuilder\\Environment\\EnvironmentInterface' => 'get2',
  'generator_classmap' => 'get3',
  'Adopt' => 'get4',
  'subEntry1' => 'get5',
  'subEntry2' => 'get6',
  'Analyse\\TestTraits' => 'get7',
  'subEntry3' => 'get8',
  'AnalyseExtension' => 'get9',
  'subEntry4' => 'get10',
  'AnalyzeModule' => 'get11',
  'subEntry5' => 'get12',
  'Base' => 'get13',
  'subEntry6' => 'get14',
  'Collect\\AdminRoutesCollector' => 'get15',
  'Collect\\CodeAnalyser' => 'get16',
  'subEntry7' => 'get17',
  'Collect\\ContainerBuilderGetter' => 'get18',
  'Collect\\DataTypesCollector' => 'get19',
  'subEntry8' => 'get20',
  'Collect\\ElementTypesCollector' => 'get21',
  'subEntry9' => 'get22',
  'Collect\\EntityTypesCollector' => 'get23',
  'subEntry10' => 'get24',
  'Collect\\EventNamesCollector' => 'get25',
  'Collect\\FieldTypesCollector' => 'get26',
  'subEntry11' => 'get27',
  'Collect\\HooksCollector10' => 'get28',
  'subEntry12' => 'get29',
  'Collect\\HooksCollector11' => 'get30',
  'subEntry13' => 'get31',
  'Collect\\HooksCollector5' => 'get32',
  'subEntry14' => 'get33',
  'Collect\\HooksCollector6' => 'get34',
  'subEntry15' => 'get35',
  'Collect\\HooksCollector7' => 'get36',
  'subEntry16' => 'get37',
  'Collect\\HooksCollector8' => 'get38',
  'subEntry17' => 'get39',
  'Collect\\HooksCollector9' => 'get40',
  'subEntry18' => 'get41',
  'Collect\\MethodCollector' => 'get42',
  'Collect\\PluginTypesCollector' => 'get43',
  'subEntry19' => 'get44',
  'subEntry20' => 'get45',
  'subEntry21' => 'get46',
  'subEntry22' => 'get47',
  'Collect\\ServiceTagTypesCollector' => 'get48',
  'subEntry23' => 'get49',
  'subEntry24' => 'get50',
  'subEntry25' => 'get51',
  'Collect\\ServicesCollector' => 'get52',
  'subEntry26' => 'get53',
  'subEntry27' => 'get54',
  'subEntry28' => 'get55',
  'Collect5' => 'get56',
  'subEntry29' => 'get57',
  'subEntry30' => 'get58',
  'Collect6' => 'get59',
  'subEntry31' => 'get60',
  'subEntry32' => 'get61',
  'Collect7' => 'get62',
  'subEntry33' => 'get63',
  'subEntry34' => 'get64',
  'Configuration' => 'get65',
  'subEntry35' => 'get66',
  'subEntry36' => 'get67',
  'Generate\\ComponentClassHandler' => 'get68',
  'subEntry37' => 'get69',
  'Generate\\ComponentCollector' => 'get70',
  'subEntry38' => 'get71',
  'subEntry39' => 'get72',
  'Generate\\FileAssembler' => 'get73',
  'ReportAdminRoutes' => 'get74',
  'subEntry40' => 'get75',
  'ReportDataTypes' => 'get76',
  'subEntry41' => 'get77',
  'ReportElementTypes' => 'get78',
  'subEntry42' => 'get79',
  'ReportEntityTypes' => 'get80',
  'subEntry43' => 'get81',
  'ReportEventNames' => 'get82',
  'subEntry44' => 'get83',
  'ReportFieldTypes' => 'get84',
  'subEntry45' => 'get85',
  'ReportHookData' => 'get86',
  'subEntry46' => 'get87',
  'ReportHookDataFolder' => 'get88',
  'subEntry47' => 'get89',
  'ReportHookGroups' => 'get90',
  'subEntry48' => 'get91',
  'ReportHookPresets' => 'get92',
  'subEntry49' => 'get93',
  'ReportPluginData' => 'get94',
  'subEntry50' => 'get95',
  'ReportServiceData' => 'get96',
  'subEntry51' => 'get97',
  'ReportServiceTags' => 'get98',
  'subEntry52' => 'get99',
  'ReportSummary' => 'get100',
  'subEntry53' => 'get101',
  'subEntry54' => 'get102',
  'subEntry55' => 'get103',
  'subEntry56' => 'get104',
  'subEntry57' => 'get105',
  'subEntry58' => 'get106',
  'subEntry59' => 'get107',
  'subEntry60' => 'get108',
  'subEntry61' => 'get109',
  'subEntry62' => 'get110',
  'subEntry63' => 'get111',
  'subEntry64' => 'get112',
  'subEntry65' => 'get113',
  'Testing\\CollectTesting10' => 'get114',
  'subEntry66' => 'get115',
  'subEntry67' => 'get116',
  'subEntry68' => 'get117',
  'subEntry69' => 'get118',
  'subEntry70' => 'get119',
  'subEntry71' => 'get120',
  'subEntry72' => 'get121',
  'subEntry73' => 'get122',
  'subEntry74' => 'get123',
  'subEntry75' => 'get124',
  'subEntry76' => 'get125',
  'subEntry77' => 'get126',
  'subEntry78' => 'get127',
  'Testing\\CollectTesting11' => 'get128',
  'subEntry79' => 'get129',
  'subEntry80' => 'get130',
  'subEntry81' => 'get131',
  'subEntry82' => 'get132',
  'subEntry83' => 'get133',
  'subEntry84' => 'get134',
  'subEntry85' => 'get135',
  'subEntry86' => 'get136',
  'subEntry87' => 'get137',
  'subEntry88' => 'get138',
  'subEntry89' => 'get139',
  'subEntry90' => 'get140',
  'subEntry91' => 'get141',
  'Testing\\CollectTesting7' => 'get142',
  'subEntry92' => 'get143',
  'subEntry93' => 'get144',
  'Testing\\CollectTesting8' => 'get145',
  'subEntry94' => 'get146',
  'subEntry95' => 'get147',
  'subEntry96' => 'get148',
  'subEntry97' => 'get149',
  'subEntry98' => 'get150',
  'subEntry99' => 'get151',
  'subEntry100' => 'get152',
  'subEntry101' => 'get153',
  'subEntry102' => 'get154',
  'subEntry103' => 'get155',
  'subEntry104' => 'get156',
  'subEntry105' => 'get157',
  'subEntry106' => 'get158',
  'Testing\\CollectTesting9' => 'get159',
  'subEntry107' => 'get160',
  'subEntry108' => 'get161',
  'subEntry109' => 'get162',
  'subEntry110' => 'get163',
  'subEntry111' => 'get164',
  'subEntry112' => 'get165',
  'subEntry113' => 'get166',
  'subEntry114' => 'get167',
  'subEntry115' => 'get168',
  'subEntry116' => 'get169',
  'subEntry117' => 'get170',
  'subEntry118' => 'get171',
  'subEntry119' => 'get172',
  'Generate|module' => 'get173',
  'Generate|profile' => 'get174',
  'Collect\\HooksCollector' => 'get175',
  'Collect' => 'get176',
  'Collect.unversioned' => 'get177',
  'subEntry120' => 'get178',
  'subEntry121' => 'get179',
  'subEntry122' => 'get180',
  'subEntry123' => 'get181',
  'subEntry124' => 'get182',
  'subEntry125' => 'get183',
  'subEntry126' => 'get184',
  'subEntry127' => 'get185',
  'subEntry128' => 'get186',
  'subEntry129' => 'get187',
  'subEntry130' => 'get188',
  'subEntry131' => 'get189',
  'subEntry132' => 'get190',
  'Testing\\CollectTesting' => 'get191',
  'DrupalCodeBuilder\\Task\\Collect\\HooksCollector' => 'get192',
  'DrupalCodeBuilder\\Task\\Generate\\ComponentClassHandler' => 'get193',
  'subEntry133' => 'get194',
  'DrupalCodeBuilder\\Task\\Collect\\ContainerBuilderGetter' => 'get195',
  'DrupalCodeBuilder\\Task\\Collect\\MethodCollector' => 'get196',
  'DrupalCodeBuilder\\Task\\Collect\\CodeAnalyser' => 'get197',
  'subEntry134' => 'get198',
  'DrupalCodeBuilder\\Task\\ReportHookData' => 'get199',
  'subEntry135' => 'get200',
);

    protected function get1()
    {
        $object = new DrupalCodeBuilder\Environment\DefaultEnvironment();
        return $object;
    }

    protected function get2()
    {
        return $this->delegateContainer->get('environment');
    }

    protected function get3()
    {
        return [
            'AdminSettingsForm' => [
            7 => 'AdminSettingsForm7',
        ],
            'DrushCommand' => [
            11 => 'DrushCommand',
            10 => 'DrushCommand',
            9 => 'DrushCommand',
            8 => 'DrushCommandUsingService',
            7 => 'DrushCommandUsingService',
            6 => 'DrushCommandUsingService',
            5 => 'DrushCommandUsingService',
        ],
            'Form' => [
            7 => 'Form7',
        ],
            'HookImplementationProcedural' => [
            6 => 'HookImplementationProcedural6',
        ],
            'InfoModule' => [
            5 => 'InfoModule5',
            6 => 'InfoModule6',
            7 => 'InfoModule7',
            8 => 'InfoModule8',
            9 => 'InfoModule9',
        ],
            'Module' => [
            7 => 'Module7AndLower',
            6 => 'Module7AndLower',
            5 => 'Module7AndLower',
            8 => 'Module8',
            10 => 'Module9And10',
            9 => 'Module9And10',
        ],
            'Permission' => [
            7 => 'Permission7',
        ],
            'RouterItem' => [
            7 => 'RouterItem7',
        ],
            'Tests' => [
            6 => 'Tests6',
            7 => 'Tests7',
        ],
        ];
    }

    protected function get5()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get6()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Task\\Generate\\ComponentClassHandler');
    }

    protected function get4()
    {
        $object = new \DrupalCodeBuilder\Task\Adopt($this->get5(), $this->get6());
        return $object;
    }

    protected function get8()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get7()
    {
        $object = new \DrupalCodeBuilder\Task\Analyse\TestTraits($this->get8());
        return $object;
    }

    protected function get10()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get9()
    {
        $object = new \DrupalCodeBuilder\Task\AnalyseExtension($this->get10());
        return $object;
    }

    protected function get12()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get11()
    {
        $object = new \DrupalCodeBuilder\Task\AnalyzeModule($this->get12());
        return $object;
    }

    protected function get14()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get13()
    {
        $object = new \DrupalCodeBuilder\Task\Base($this->get14());
        return $object;
    }

    protected function get15()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\AdminRoutesCollector();
        return $object;
    }

    protected function get17()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get16()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\CodeAnalyser($this->get17());
        return $object;
    }

    protected function get18()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\ContainerBuilderGetter();
        return $object;
    }

    protected function get20()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get19()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\DataTypesCollector($this->get20());
        return $object;
    }

    protected function get22()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get21()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\ElementTypesCollector($this->get22());
        return $object;
    }

    protected function get24()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get23()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\EntityTypesCollector($this->get24());
        return $object;
    }

    protected function get25()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\EventNamesCollector();
        return $object;
    }

    protected function get27()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get26()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\FieldTypesCollector($this->get27());
        return $object;
    }

    protected function get29()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get28()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\HooksCollector10($this->get29());
        return $object;
    }

    protected function get31()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get30()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\HooksCollector11($this->get31());
        return $object;
    }

    protected function get33()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get32()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\HooksCollector5($this->get33());
        return $object;
    }

    protected function get35()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get34()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\HooksCollector6($this->get35());
        return $object;
    }

    protected function get37()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get36()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\HooksCollector7($this->get37());
        return $object;
    }

    protected function get39()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get38()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\HooksCollector8($this->get39());
        return $object;
    }

    protected function get41()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get40()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\HooksCollector9($this->get41());
        return $object;
    }

    protected function get42()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\MethodCollector();
        return $object;
    }

    protected function get44()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get45()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Task\\Collect\\ContainerBuilderGetter');
    }

    protected function get46()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Task\\Collect\\MethodCollector');
    }

    protected function get47()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Task\\Collect\\CodeAnalyser');
    }

    protected function get43()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\PluginTypesCollector($this->get44(), $this->get45(), $this->get46(), $this->get47());
        return $object;
    }

    protected function get49()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get50()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Task\\Collect\\ContainerBuilderGetter');
    }

    protected function get51()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Task\\Collect\\MethodCollector');
    }

    protected function get48()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\ServiceTagTypesCollector($this->get49(), $this->get50(), $this->get51());
        return $object;
    }

    protected function get53()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get54()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Task\\Collect\\ContainerBuilderGetter');
    }

    protected function get55()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Task\\Collect\\CodeAnalyser');
    }

    protected function get52()
    {
        $object = new \DrupalCodeBuilder\Task\Collect\ServicesCollector($this->get53(), $this->get54(), $this->get55());
        return $object;
    }

    protected function get57()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get58()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Task\\Collect\\HooksCollector');
    }

    protected function get56()
    {
        $object = new \DrupalCodeBuilder\Task\Collect5($this->get57(), $this->get58());
        return $object;
    }

    protected function get60()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get61()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Task\\Collect\\HooksCollector');
    }

    protected function get59()
    {
        $object = new \DrupalCodeBuilder\Task\Collect6($this->get60(), $this->get61());
        return $object;
    }

    protected function get63()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get64()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Task\\Collect\\HooksCollector');
    }

    protected function get62()
    {
        $object = new \DrupalCodeBuilder\Task\Collect7($this->get63(), $this->get64());
        return $object;
    }

    protected function get66()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get67()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Task\\Generate\\ComponentClassHandler');
    }

    protected function get65()
    {
        $object = new \DrupalCodeBuilder\Task\Configuration($this->get66(), $this->get67());
        return $object;
    }

    protected function get69()
    {
        return $this->delegateContainer->get('generator_classmap');
    }

    protected function get68()
    {
        $object = new \DrupalCodeBuilder\Task\Generate\ComponentClassHandler($this->get69());
        return $object;
    }

    protected function get71()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get72()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Task\\Generate\\ComponentClassHandler');
    }

    protected function get70()
    {
        $object = new \DrupalCodeBuilder\Task\Generate\ComponentCollector($this->get71(), $this->get72());
        return $object;
    }

    protected function get73()
    {
        $object = new \DrupalCodeBuilder\Task\Generate\FileAssembler();
        return $object;
    }

    protected function get75()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get74()
    {
        $object = new \DrupalCodeBuilder\Task\ReportAdminRoutes($this->get75());
        return $object;
    }

    protected function get77()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get76()
    {
        $object = new \DrupalCodeBuilder\Task\ReportDataTypes($this->get77());
        return $object;
    }

    protected function get79()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get78()
    {
        $object = new \DrupalCodeBuilder\Task\ReportElementTypes($this->get79());
        return $object;
    }

    protected function get81()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get80()
    {
        $object = new \DrupalCodeBuilder\Task\ReportEntityTypes($this->get81());
        return $object;
    }

    protected function get83()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get82()
    {
        $object = new \DrupalCodeBuilder\Task\ReportEventNames($this->get83());
        return $object;
    }

    protected function get85()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get84()
    {
        $object = new \DrupalCodeBuilder\Task\ReportFieldTypes($this->get85());
        return $object;
    }

    protected function get87()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get86()
    {
        $object = new \DrupalCodeBuilder\Task\ReportHookData($this->get87());
        return $object;
    }

    protected function get89()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get88()
    {
        $object = new \DrupalCodeBuilder\Task\ReportHookDataFolder($this->get89());
        return $object;
    }

    protected function get91()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Task\\ReportHookData');
    }

    protected function get90()
    {
        $object = new \DrupalCodeBuilder\Task\ReportHookGroups($this->get91());
        return $object;
    }

    protected function get93()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get92()
    {
        $object = new \DrupalCodeBuilder\Task\ReportHookPresets($this->get93());
        return $object;
    }

    protected function get95()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get94()
    {
        $object = new \DrupalCodeBuilder\Task\ReportPluginData($this->get95());
        return $object;
    }

    protected function get97()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get96()
    {
        $object = new \DrupalCodeBuilder\Task\ReportServiceData($this->get97());
        return $object;
    }

    protected function get99()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get98()
    {
        $object = new \DrupalCodeBuilder\Task\ReportServiceTags($this->get99());
        return $object;
    }

    protected function get101()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get103()
    {
        return $this->delegateContainer->get('Analyse\\TestTraits');
    }

    protected function get104()
    {
        return $this->delegateContainer->get('ReportAdminRoutes');
    }

    protected function get105()
    {
        return $this->delegateContainer->get('ReportDataTypes');
    }

    protected function get106()
    {
        return $this->delegateContainer->get('ReportElementTypes');
    }

    protected function get107()
    {
        return $this->delegateContainer->get('ReportEntityTypes');
    }

    protected function get108()
    {
        return $this->delegateContainer->get('ReportEventNames');
    }

    protected function get109()
    {
        return $this->delegateContainer->get('ReportFieldTypes');
    }

    protected function get110()
    {
        return $this->delegateContainer->get('ReportHookData');
    }

    protected function get111()
    {
        return $this->delegateContainer->get('ReportPluginData');
    }

    protected function get112()
    {
        return $this->delegateContainer->get('ReportServiceData');
    }

    protected function get113()
    {
        return $this->delegateContainer->get('ReportServiceTags');
    }

    protected function get102()
    {
        return [
            'Analyse\\TestTraits' => $this->get103(),
            'ReportAdminRoutes' => $this->get104(),
            'ReportDataTypes' => $this->get105(),
            'ReportElementTypes' => $this->get106(),
            'ReportEntityTypes' => $this->get107(),
            'ReportEventNames' => $this->get108(),
            'ReportFieldTypes' => $this->get109(),
            'ReportHookData' => $this->get110(),
            'ReportPluginData' => $this->get111(),
            'ReportServiceData' => $this->get112(),
            'ReportServiceTags' => $this->get113(),
        ];
    }

    protected function get100()
    {
        $object = new \DrupalCodeBuilder\Task\ReportSummary($this->get101());
        $object->setReportHelpers($this->get102());
        return $object;
    }

    protected function get115()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get117()
    {
        return $this->delegateContainer->get('Analyse\\TestTraits');
    }

    protected function get118()
    {
        return $this->delegateContainer->get('Collect\\AdminRoutesCollector');
    }

    protected function get119()
    {
        return $this->delegateContainer->get('Collect\\DataTypesCollector');
    }

    protected function get120()
    {
        return $this->delegateContainer->get('Collect\\ElementTypesCollector');
    }

    protected function get121()
    {
        return $this->delegateContainer->get('Collect\\EntityTypesCollector');
    }

    protected function get122()
    {
        return $this->delegateContainer->get('Collect\\EventNamesCollector');
    }

    protected function get123()
    {
        return $this->delegateContainer->get('Collect\\FieldTypesCollector');
    }

    protected function get124()
    {
        return $this->delegateContainer->get('Collect\\PluginTypesCollector');
    }

    protected function get125()
    {
        return $this->delegateContainer->get('Collect\\ServiceTagTypesCollector');
    }

    protected function get126()
    {
        return $this->delegateContainer->get('Collect\\ServicesCollector');
    }

    protected function get127()
    {
        return $this->delegateContainer->get('Collect\\HooksCollector');
    }

    protected function get116()
    {
        return [
            'Analyse\\TestTraits' => $this->get117(),
            'Collect\\AdminRoutesCollector' => $this->get118(),
            'Collect\\DataTypesCollector' => $this->get119(),
            'Collect\\ElementTypesCollector' => $this->get120(),
            'Collect\\EntityTypesCollector' => $this->get121(),
            'Collect\\EventNamesCollector' => $this->get122(),
            'Collect\\FieldTypesCollector' => $this->get123(),
            'Collect\\PluginTypesCollector' => $this->get124(),
            'Collect\\ServiceTagTypesCollector' => $this->get125(),
            'Collect\\ServicesCollector' => $this->get126(),
            'Collect\\HooksCollector' => $this->get127(),
        ];
    }

    protected function get114()
    {
        $object = new \DrupalCodeBuilder\Task\Testing\CollectTesting10($this->get115());
        $object->setCollectors($this->get116());
        return $object;
    }

    protected function get129()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get131()
    {
        return $this->delegateContainer->get('Analyse\\TestTraits');
    }

    protected function get132()
    {
        return $this->delegateContainer->get('Collect\\AdminRoutesCollector');
    }

    protected function get133()
    {
        return $this->delegateContainer->get('Collect\\DataTypesCollector');
    }

    protected function get134()
    {
        return $this->delegateContainer->get('Collect\\ElementTypesCollector');
    }

    protected function get135()
    {
        return $this->delegateContainer->get('Collect\\EntityTypesCollector');
    }

    protected function get136()
    {
        return $this->delegateContainer->get('Collect\\EventNamesCollector');
    }

    protected function get137()
    {
        return $this->delegateContainer->get('Collect\\FieldTypesCollector');
    }

    protected function get138()
    {
        return $this->delegateContainer->get('Collect\\PluginTypesCollector');
    }

    protected function get139()
    {
        return $this->delegateContainer->get('Collect\\ServiceTagTypesCollector');
    }

    protected function get140()
    {
        return $this->delegateContainer->get('Collect\\ServicesCollector');
    }

    protected function get141()
    {
        return $this->delegateContainer->get('Collect\\HooksCollector');
    }

    protected function get130()
    {
        return [
            'Analyse\\TestTraits' => $this->get131(),
            'Collect\\AdminRoutesCollector' => $this->get132(),
            'Collect\\DataTypesCollector' => $this->get133(),
            'Collect\\ElementTypesCollector' => $this->get134(),
            'Collect\\EntityTypesCollector' => $this->get135(),
            'Collect\\EventNamesCollector' => $this->get136(),
            'Collect\\FieldTypesCollector' => $this->get137(),
            'Collect\\PluginTypesCollector' => $this->get138(),
            'Collect\\ServiceTagTypesCollector' => $this->get139(),
            'Collect\\ServicesCollector' => $this->get140(),
            'Collect\\HooksCollector' => $this->get141(),
        ];
    }

    protected function get128()
    {
        $object = new \DrupalCodeBuilder\Task\Testing\CollectTesting11($this->get129());
        $object->setCollectors($this->get130());
        return $object;
    }

    protected function get143()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get144()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Task\\Collect\\HooksCollector');
    }

    protected function get142()
    {
        $object = new \DrupalCodeBuilder\Task\Testing\CollectTesting7($this->get143(), $this->get144());
        return $object;
    }

    protected function get146()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get148()
    {
        return $this->delegateContainer->get('Analyse\\TestTraits');
    }

    protected function get149()
    {
        return $this->delegateContainer->get('Collect\\AdminRoutesCollector');
    }

    protected function get150()
    {
        return $this->delegateContainer->get('Collect\\DataTypesCollector');
    }

    protected function get151()
    {
        return $this->delegateContainer->get('Collect\\ElementTypesCollector');
    }

    protected function get152()
    {
        return $this->delegateContainer->get('Collect\\EntityTypesCollector');
    }

    protected function get153()
    {
        return $this->delegateContainer->get('Collect\\EventNamesCollector');
    }

    protected function get154()
    {
        return $this->delegateContainer->get('Collect\\FieldTypesCollector');
    }

    protected function get155()
    {
        return $this->delegateContainer->get('Collect\\PluginTypesCollector');
    }

    protected function get156()
    {
        return $this->delegateContainer->get('Collect\\ServiceTagTypesCollector');
    }

    protected function get157()
    {
        return $this->delegateContainer->get('Collect\\ServicesCollector');
    }

    protected function get158()
    {
        return $this->delegateContainer->get('Collect\\HooksCollector');
    }

    protected function get147()
    {
        return [
            'Analyse\\TestTraits' => $this->get148(),
            'Collect\\AdminRoutesCollector' => $this->get149(),
            'Collect\\DataTypesCollector' => $this->get150(),
            'Collect\\ElementTypesCollector' => $this->get151(),
            'Collect\\EntityTypesCollector' => $this->get152(),
            'Collect\\EventNamesCollector' => $this->get153(),
            'Collect\\FieldTypesCollector' => $this->get154(),
            'Collect\\PluginTypesCollector' => $this->get155(),
            'Collect\\ServiceTagTypesCollector' => $this->get156(),
            'Collect\\ServicesCollector' => $this->get157(),
            'Collect\\HooksCollector' => $this->get158(),
        ];
    }

    protected function get145()
    {
        $object = new \DrupalCodeBuilder\Task\Testing\CollectTesting8($this->get146());
        $object->setCollectors($this->get147());
        return $object;
    }

    protected function get160()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get162()
    {
        return $this->delegateContainer->get('Analyse\\TestTraits');
    }

    protected function get163()
    {
        return $this->delegateContainer->get('Collect\\AdminRoutesCollector');
    }

    protected function get164()
    {
        return $this->delegateContainer->get('Collect\\DataTypesCollector');
    }

    protected function get165()
    {
        return $this->delegateContainer->get('Collect\\ElementTypesCollector');
    }

    protected function get166()
    {
        return $this->delegateContainer->get('Collect\\EntityTypesCollector');
    }

    protected function get167()
    {
        return $this->delegateContainer->get('Collect\\EventNamesCollector');
    }

    protected function get168()
    {
        return $this->delegateContainer->get('Collect\\FieldTypesCollector');
    }

    protected function get169()
    {
        return $this->delegateContainer->get('Collect\\PluginTypesCollector');
    }

    protected function get170()
    {
        return $this->delegateContainer->get('Collect\\ServiceTagTypesCollector');
    }

    protected function get171()
    {
        return $this->delegateContainer->get('Collect\\ServicesCollector');
    }

    protected function get172()
    {
        return $this->delegateContainer->get('Collect\\HooksCollector');
    }

    protected function get161()
    {
        return [
            'Analyse\\TestTraits' => $this->get162(),
            'Collect\\AdminRoutesCollector' => $this->get163(),
            'Collect\\DataTypesCollector' => $this->get164(),
            'Collect\\ElementTypesCollector' => $this->get165(),
            'Collect\\EntityTypesCollector' => $this->get166(),
            'Collect\\EventNamesCollector' => $this->get167(),
            'Collect\\FieldTypesCollector' => $this->get168(),
            'Collect\\PluginTypesCollector' => $this->get169(),
            'Collect\\ServiceTagTypesCollector' => $this->get170(),
            'Collect\\ServicesCollector' => $this->get171(),
            'Collect\\HooksCollector' => $this->get172(),
        ];
    }

    protected function get159()
    {
        $object = new \DrupalCodeBuilder\Task\Testing\CollectTesting9($this->get160());
        $object->setCollectors($this->get161());
        return $object;
    }

    protected function get173()
    {
        return $this->resolveFactory([
            0 => 'DrupalCodeBuilder\\DependencyInjection\\ServiceFactories',
            1 => 'createGenerator',
        ], 'Generate|module', [
            'root_component_type' => 'module',
        ]);
    }

    protected function get174()
    {
        return $this->resolveFactory([
            0 => 'DrupalCodeBuilder\\DependencyInjection\\ServiceFactories',
            1 => 'createGenerator',
        ], 'Generate|profile', [
            'root_component_type' => 'profile',
        ]);
    }

    protected function get175()
    {
        return $this->resolveFactory([
            0 => 'DrupalCodeBuilder\\DependencyInjection\\ServiceFactories',
            1 => 'createVersioned',
        ], 'Collect\\HooksCollector');
    }

    protected function get176()
    {
        return $this->resolveFactory([
            0 => 'DrupalCodeBuilder\\DependencyInjection\\ServiceFactories',
            1 => 'createVersioned',
        ], 'Collect');
    }

    protected function get178()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get180()
    {
        return $this->delegateContainer->get('Analyse\\TestTraits');
    }

    protected function get181()
    {
        return $this->delegateContainer->get('Collect\\AdminRoutesCollector');
    }

    protected function get182()
    {
        return $this->delegateContainer->get('Collect\\DataTypesCollector');
    }

    protected function get183()
    {
        return $this->delegateContainer->get('Collect\\ElementTypesCollector');
    }

    protected function get184()
    {
        return $this->delegateContainer->get('Collect\\EntityTypesCollector');
    }

    protected function get185()
    {
        return $this->delegateContainer->get('Collect\\EventNamesCollector');
    }

    protected function get186()
    {
        return $this->delegateContainer->get('Collect\\FieldTypesCollector');
    }

    protected function get187()
    {
        return $this->delegateContainer->get('Collect\\PluginTypesCollector');
    }

    protected function get188()
    {
        return $this->delegateContainer->get('Collect\\ServiceTagTypesCollector');
    }

    protected function get189()
    {
        return $this->delegateContainer->get('Collect\\ServicesCollector');
    }

    protected function get190()
    {
        return $this->delegateContainer->get('Collect\\HooksCollector');
    }

    protected function get179()
    {
        return [
            'Analyse\\TestTraits' => $this->get180(),
            'Collect\\AdminRoutesCollector' => $this->get181(),
            'Collect\\DataTypesCollector' => $this->get182(),
            'Collect\\ElementTypesCollector' => $this->get183(),
            'Collect\\EntityTypesCollector' => $this->get184(),
            'Collect\\EventNamesCollector' => $this->get185(),
            'Collect\\FieldTypesCollector' => $this->get186(),
            'Collect\\PluginTypesCollector' => $this->get187(),
            'Collect\\ServiceTagTypesCollector' => $this->get188(),
            'Collect\\ServicesCollector' => $this->get189(),
            'Collect\\HooksCollector' => $this->get190(),
        ];
    }

    protected function get177()
    {
        $object = new \DrupalCodeBuilder\Task\Collect($this->get178());
        $object->setCollectors($this->get179());
        return $object;
    }

    protected function get191()
    {
        return $this->resolveFactory([
            0 => 'DrupalCodeBuilder\\DependencyInjection\\ServiceFactories',
            1 => 'createVersioned',
        ], 'Testing\\CollectTesting');
    }

    protected function get192()
    {
        return $this->delegateContainer->get('Collect\\HooksCollector');
    }

    protected function get194()
    {
        return $this->delegateContainer->get('generator_classmap');
    }

    protected function get193()
    {
        $object = new DrupalCodeBuilder\Task\Generate\ComponentClassHandler($this->get194());
        return $object;
    }

    protected function get195()
    {
        $object = new DrupalCodeBuilder\Task\Collect\ContainerBuilderGetter();
        return $object;
    }

    protected function get196()
    {
        $object = new DrupalCodeBuilder\Task\Collect\MethodCollector();
        return $object;
    }

    protected function get198()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get197()
    {
        $object = new DrupalCodeBuilder\Task\Collect\CodeAnalyser($this->get198());
        return $object;
    }

    protected function get200()
    {
        return $this->delegateContainer->get('DrupalCodeBuilder\\Environment\\EnvironmentInterface');
    }

    protected function get199()
    {
        $object = new DrupalCodeBuilder\Task\ReportHookData($this->get200());
        return $object;
    }

}
